version: "3.9"

services:
  # 1. æ•°æ®åº“æœåŠ¡
  mysqldb:
    image: mysql:8.0
    container_name: library-db
    platform: linux/arm64 
    environment:
      MYSQL_ROOT_PASSWORD: 3541275Hh!  
      MYSQL_DATABASE: reactlibrarydatabase
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - library-net


  # 2. åç«¯æœåŠ¡
  backend:
    image: huangkouhou/library-backend:latest
    container_name: library-backend
    restart: always
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/reactlibrarydatabase?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      STRIPE_KEY_SECRET: ${STRIPE_KEY_SECRET}
      OKTA_OAUTH2_AUDIENCE: https://library.penghuang.dev
      OKTA_OAUTH2_ISSUER: ${OKTA_OAUTH2_ISSUER}
      OKTA_OAUTH2_CLIENT_ID: ${OKTA_OAUTH2_CLIENT_ID}
      
    depends_on:
      - mysqldb
    networks:
      - library-net


  # 3. å‰ç«¯æœåŠ¡
  frontend:
    build: ./03-frontend/react-library
    container_name: library-frontend
    restart: always
    expose:
      - "80"
    networks:
      - library-net

  # 4. ç½‘å…³ Nginx
  nginx:
      image: nginx:alpine
      container_name: library-gateway
      restart: always
      ports:
        - "80:80"
        - "443:443"  
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        # ğŸ‘‡ æ–°å¢ï¼šæŠŠå®¿ä¸»æœºçš„è¯ä¹¦æŒ‚è½½åˆ°å®¹å™¨å†…éƒ¨
        - /etc/letsencrypt/live/library.penghuang.dev/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
        - /etc/letsencrypt/live/library.penghuang.dev/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
      depends_on:
        - backend
        - frontend
      networks:
        - library-net

volumes:
  mysql_data:

networks:
  library-net:
    driver: bridge