version: "3.9"

services:
  # 1. 数据库服务
  mysqldb:
    image: mysql:8.0
    container_name: library-db
    platform: linux/arm64 
    environment:
      MYSQL_ROOT_PASSWORD: 3541275Hh!  
      MYSQL_DATABASE: reactlibrarydatabase
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - library-net
    restart: always

  # 2. 后端服务
  backend:
    image: huangkouhou/library-backend:latest
    container_name: library-backend
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/reactlibrarydatabase?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 3541275Hh!
      OKTA_OAUTH2_AUDIENCE: https://library.penghuang.dev
      OKTA_OAUTH2_ISSUER: https://dev-tijrtha6cwckmy1o.us.auth0.com/
      
    depends_on:
      - mysqldb
    networks:
      - library-net
    restart: always

  # # 3. 前端服务
  # frontend:
  #   build: ./03-frontend/react-library
  #   container_name: library-frontend
  #   expose:
  #     - "80"
  #   networks:
  #     - library-net

  # # 4. 网关 Nginx
  # nginx:
  #   image: nginx:alpine
  #   container_name: library-gateway
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - backend
  #     - frontend
  #   networks:
  #     - library-net

volumes:
  mysql_data:

networks:
  library-net:
    driver: bridge