name: Frontend cicd
on:
  push:
    branches: [ "feature/cloud-deploy" ]
    paths:
      - '03-frontend/react-library/**' # ğŸ‘ˆ åªæœ‰å‰ç«¯å˜åŠ¨æ‰è§¦å‘

jobs:
  build-react:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./03-frontend/react-library # ğŸ‘ˆ è¿›å…¥å‰ç«¯å­ç›®å½•
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # æˆ–è€…ä½ ç”¨çš„ç‰ˆæœ¬
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: npm run build